### ISSUE TITLE
Filtros não funcionam para um departamento específico

### ISSUE THREAD

**Issue by matheuscfrade** [SEI-Pro/sei-pro#15]
As funções relacionadas a "Agrupar lista de processos por marcadores, tipo, responsável ou ponto de controle" funcionam para alguns departamentos mas um em específico não está carregando a opção.

**Comment by pedrohsoaresadv** [comment]
Olá @matheuscfrade 

Acabamos de lançar a versão 1.2, com compatibilidade para o SEI 4.0. 

Nela corrigi alguns bugs relacionados a diversas funcionalidades. 

Peço que verifique novamente a partir dessa versão mais recente.

Caso o erro persista, deixe-nos informado reabrindo esse tópico.
