### ISSUE TITLE
SEI 4.0 - Incompatibilidade com o filtro "atribuído para mim"

### ISSUE THREAD

**Issue by kelsensantos** [SEI-Pro/sei-pro#16]
Na versão 4.0 do SEI o filtro "atribuído para mim" quebra. Ao selecionar o filtro, se a extensão estiver ativada, não é possível mais "desselecionar" (o "x" não funciona). Logo que possível posto imagem.

**Comment by tfbbueno** [comment]
Estou enfrentando o mesmo problema por aqui.

**Comment by pedrohsoaresadv** [comment]
@tfbbueno e @kelsensantos

**Comment by seipro** [comment]
Olá @tfbbueno e @kelsensantos 

A versão > 1.4 corrigiu o problema informado.
