### ISSUE TITLE
SEI 4.0 - Os filtros de agrupadores ocupam apenas parte da tela

### ISSUE THREAD

**Issue by kelsensantos** [SEI-Pro/sei-pro#17]
Na versão 4.0 do SEI os filtros de agrupadores do SEI Pro só conseguem abranger os processos "tramitados" para a unidade (não alcança os processos "gerados"), e fica ocupando só a metade da tela relativa àqueles. Logo que possível posto imagem.

**Comment by pedrohsoaresadv** [comment]
Olá @kelsensantos 

Acabamos de lançar a versão 1.2. Nela corrigi alguns bugs relacionados ao agrupamento de arquivos, conforme descrito em seu relato. Peço que verifique novamente a partir dessa versão mais recente.

Deixe-nos saber se o bug ainda está visível para você.
