### ISSUE TITLE
Lentidão para abrir documentos

### ISSUE THREAD

**Issue by totroi** [SEI-Pro/sei-pro#18]
Ao acessar o processo no SEI e clicar em um documento, por vezes simplesmente nada acontece. Ficam muitos segundos (20, 30, 40...) sem nada acontecer, ainda que se clique em outros documentos. Como se ele estivesse aguardando resposta de alguma requisição.

Vale ressaltar que uso as extensões SEI++ e SEI+Trello. Tentei desativar o SEI++, mas não fez diferença. Já quanto ao SEI+Trello, não pretendo desativar pois não quero deixar de utilizar essa extensão.

**Comment by pedrohsoaresadv** [comment]
Olá @totroi  

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)

Se o problema persistir, gentileza abrir novo issue para averiguarmos mais de perto.
