### ISSUE TITLE
 Erro ao receber sua informações do servidor de dados. Tente novamente mais tarde. (error)

### ISSUE THREAD

**Issue by raphaelsawaki** [SEI-Pro/sei-pro#19]
O erro fica persistente na tela e a cada atualização de página ele volta.

**Comment by pedrohsoaresadv** [comment]
Olá @raphaelsawaki   

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)

Se o problema persistir, gentileza abrir novo issue para averiguarmos mais de perto.
