### ISSUE TITLE
Erro de carregamento de elementos da tela de controle de processos.

### ISSUE THREAD

**Issue by franciscoeudessb** [SEI-Pro/sei-pro#20]
Desde o final de Dezembro/2021 percebi que a extensão está causando erro ao carregar a tela de controle de processo, tanto ao realizar login, quanto ao trocar de lotação. Testei todas as extensões instaladas no navegador (Chrome) e quando removi o Sei Pro não apresentou mais esse erro. Por vezes somem os processos como na Imagem 1, ai nesse caso a solução é simplesmente clicar nas "duas torres" de Controle de Processos. E em outra situação a barra de menu lateral é carregada mais fica bem abaixo de onde deveria ficar, ai a solução é clicar em "Menu" nas opções do topo da página.

![1](https://user-images.githubusercontent.com/7564272/152528479-0fcf1b2a-8958-4a95-a81d-f633c1d90f2c.PNG)

**Comment by pedrohsoaresadv** [comment]
Olá @franciscoeudessb   

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)

Se o problema persistir, gentileza abrir novo issue para averiguarmos mais de perto.
