### ISSUE TITLE
Arrastar e soltar itens como "Anexo" no processo não está funcionando

### ISSUE THREAD

**Issue by manalista** [SEI-Pro/sei-pro#21]

**Comment by WagnerAssuncao** [comment]
Aqui também não está funcionando. 

O arquivo fica na árvore de documentos, mas não é enviado. 

![image](https://user-images.githubusercontent.com/95177819/169904877-ae682686-43ee-43fa-8458-c47f4d62a02a.png)

**Comment by pedrohsoaresadv** [comment]
Olá @manalista e @WagnerAssuncao 

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)

**Comment by WagnerAssuncao** [comment]
Olá Pedro. Obrigado pelo retorno. 

Antes da versão ser atualizada, descobrimos aqui que caso o nome do arquivo constasse um tipo de documento aceito pelo SEI, a extensão realizaria o envio. 

Contudo, após a atualização recente realizada, tal funcionalidade deixou de estar disponível completamente. 

Apenas reportando pois esta funcionalidade é de bastante importância para os trabalhos do meu setor. Agradeço se puder dar uma olhada.
