### ISSUE TITLE
Erro ao salvar o documento

### ISSUE THREAD

**Issue by klyssmannoliveira** [SEI-Pro/sei-pro#22]
Na edição de alguns documentos, o botão de salvar fica desativado e muitas vezes o documento é perdido. A imagem abaixo mostra essa condição:

![WhatsApp Image 2022-03-24 at 11 23 40](https://user-images.githubusercontent.com/56873266/159938754-b740b661-6a31-4c2f-918b-65acf1f08f16.jpeg)

**Comment by pedrohsoaresadv** [comment]
Olá @klyssmannoliveira   

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)

Se o problema persistir, gentileza abrir novo issue para averiguarmos mais de perto.
