### ISSUE TITLE
Menu suspenso abre e recolhe em seguida

### ISSUE THREAD

**Issue by rgegas** [SEI-Pro/sei-pro#23]
Ao usar a o menu suspenso retrátil, ele abre e recolhe sem que seja possível escolher os itens. Veja video anexo.

https://user-images.githubusercontent.com/103261143/162441175-2fccec2b-f852-4859-bc2e-1b9617b16da6.mp4

.

**Comment by pedrohsoaresadv** [comment]
Olá @rgegas 

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)
