### ISSUE TITLE
Botões "i" na página de configurações levam a página inexistente

### ISSUE THREAD

**Issue by rgegas** [SEI-Pro/sei-pro#24]
Os botões de informação na página de configurações da extensão no Chrome levam a páginas inexistentes, por exemplo, https://github.com/SEI-Pro/sei-pro/pages/FAVORITOS.html.

**Comment by pedrohsoaresadv** [comment]
Olá @rgegas 

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)
