### ISSUE TITLE
Erros Recentes de Abril de 2022

### ISSUE THREAD

**Issue by RoberBC** [SEI-Pro/sei-pro#25]
De umas duas semanas pra cá o SEIPro começou a dar uns erros no Crome e Firefox.
Os links para copiar os documentos da árvore somem com frequencia. 
O menu suspenso não funciona direito. Tá exibindo continuamente mesmo configurando para ocultar.
Ao abrir várias janelas do SEI ou abrir a edição de um documento, noto que parece que o SEIPro tem parte das funcionalidades dando erro.
Tudo isso surgiu agora. Uso há meses. Era ótimo.

**Comment by felipebalbinoo** [comment]
Boa noite. O SEI Pro é uma excelente ferramenta, mas seria interessante alguma ferramenta de correção automática de ortografia.

**Comment by pedrohsoaresadv** [comment]
Olá @RoberBC   

Atualizamos o SEI Pro para a versão 1.0
A atualização é automática, muito em breve estará disponível em sua máquina, corrigindo essa e outros pequenos bugs.

Aproveitamos para adicionar um monte de novas funcionalidades ;)

Se o problema persistir, gentileza abrir novo issue para averiguarmos mais de perto.
