### ISSUE TITLE
Link para processo na tela inicial com um incorreto ")" no fim

### ISSUE THREAD

**Issue by rgegas** [SEI-Pro/sei-pro#26]
Na tela inicial do processo, o link para o processo é gerado contendo um caracter ")" incorreto ao final do link, o que envia para uma página de erro e demanda novo login no SEI.
![Erro link - SEIPro](https://user-images.githubusercontent.com/103261143/173418181-caeca2fc-249b-4af9-b7ea-163b0ff1dd28.JPG)

**Comment by pedrohsoaresadv** [comment]
Olá @rgegas 

Obrigado pelo report. Já corrigi na versão 1.0.2
