### ISSUE TITLE
Extensão parou de funcionar

### ISSUE THREAD

**Issue by edsongustavo1** [SEI-Pro/sei-pro#28]
Olá boa tarde.
Primeiramente gostaria de parabenizar pelo excelente projeto que foi desenvolver a extensão SEI PRO, porém depois de tanto usufruir dos recursos que ela proporciona, a mesma deixou de funcionar no SEI, mesmo estando ativa e nenhuma de suas funcionalidades estão disponíveis quando acesso o SEI agora.

**Comment by pedrohsoaresadv** [comment]
Olá @edsongustavo1 

Fico feliz que tenha gostado do SEI Pro ;)

A pedido dos administradores do SEI em Minas Gerais e Pernambuco tive de desativar temporariamente o SEI Pro nesses estados, devido a alegação de sobrecarga dos serviços eventualmente causados pela extensão.

Todavia, após o diagnóstico mais aprofundado por esses administradores, foi identificado que a causa não estava relacionada ao SEI Pro.

Por isso, a restrição de acesso foi retirada na versão 1.0.10, já disponível no Firefox e com previsão de publicação no Chrome nessa próxima sexta (22/07/2022)
