### ISSUE TITLE
Amplo espaço vazio do lado direito da tela

### ISSUE THREAD

**Issue by mesifpr** [SEI-Pro/sei-pro#30]
![Sem título](https://user-images.githubusercontent.com/109533793/179534126-bf2fb288-8d92-42d6-8df5-b343b06af77a.png)

Muito espaço desperdiçado vazio no lado direito da tela, restringindo a visualização de documentos (ver. 1.0.5)

**Comment by pedrohsoaresadv** [comment]
Olá @mesifpr 

Identifiquei o bug reportado. Submeti a versão 1.0.10, que corrige a situação.
