### ISSUE TITLE
Menu do SEI Pro só aparece no último grupo de documentos

### ISSUE THREAD

**Issue by lukeboh** [SEI-Pro/sei-pro#32]
Não é possível duplicar documento de outro grupo de documentos além do último (no exemplo VII). Isso porque o menu do SEI PRO só é apresentado nesse grupo. Nos anteriores ele não é exibido. Esse problema eu percebia desde a versão mais antiga do SEI. [evidência](https://youtu.be/P-LPD0tON3o).

Solução de contorno: **usar o copiar documento para outro processo e usar o número do mesmo processo.**

**Comment by pedrohsoaresadv** [comment]
Olá @lukeboh 

Acabamos de lançar a versão 1.2. Nela corrigi alguns bugs relacionados ao menu da árvore de documentos, conforme descrito em seu relato. Peço que verifique novamente a partir dessa versão mais recente.

Deixe-nos saber se o bug ainda está visível para você.
