### ISSUE TITLE
Janela do editor de texto sem barra de rolagem

### ISSUE THREAD

**Issue by rgegas** [SEI-Pro/sei-pro#33]
Uso o SEI na ANAC (versão 3.1.7). Diversas vezes a barra de rolagem não aparece quando a janela de edição é aberta. O problema é solucionado se redimensionar a janela.

**Comment by pedrohsoaresadv** [comment]
Prezado @joseolinda 

Depois de muita pesquisa, praticamente rescrevendo do zero o SEI Pro, pude identificar que esse problema estava se refletindo por diversas extensões usadas no Chrome, inclusive o Google Tradutor. Aparentemente a última atualização do Chrome (Versão 104.0.5112.79) ocasionou algum comportamento indesejado na função nativa do SEI que, combinado com extensões, não executava a rotina de habilita o botão de Salvar do editor do SEI.
A solução aplicada no SEI Pro foi forçar o carregamento do botão de salvar caso o editor não carregue adequadamente essa função nativa.

Espero que tenha sido claro e obrigado pelo feedback
