### ISSUE TITLE
CRÍTICO: Botão Salvar desabilitado na janela de edição

### ISSUE THREAD

**Issue by rgegas** [SEI-Pro/sei-pro#34]
Uso o SEI na ANAC (versão 3.1.7). Por diversas vezes o botão de salvar fica desabilitado após diversas alterações no documento, sendo impossível manter as alterações - preciso copiar tudo para o Word, fechar e re-editar o texto. O problema não ocorre quando desabilito a extensão SEI Pro.

**Comment by pedrohsoaresadv** [comment]
Prezado @rgegas  

Depois de muita pesquisa, praticamente rescrevendo do zero o SEI Pro, pude identificar que esse problema estava se refletindo por diversas extensões usadas no Chrome, inclusive o Google Tradutor. Aparentemente a última atualização do Chrome (Versão 104.0.5112.79) ocasionou algum comportamento indesejado na função nativa do SEI que, combinado com extensões, não executava a rotina de habilita o botão de Salvar do editor do SEI.
A solução aplicada no SEI Pro foi forçar o carregamento do botão de salvar caso o editor não carregue adequadamente essa função nativa.

Espero que tenha sido claro e obrigado pelo feedback

**Comment by rgegas** [comment]
Muito obrigado Pedro! Caso o problema se repita lhe avisarei.

Atenciosamente,

Reinaldo

Em qui., 11 de ago. de 2022 19:27, Pedro Soares ***@***.***>
escreveu:
