### ISSUE TITLE
Estilo Avançado e Favoritos são inabilitados sempre que desconecta o usuário

### ISSUE THREAD

**Issue by HamandaCabral** [SEI-Pro/sei-pro#35]
Sempre que reinicia o usuário, todos os favoritos desaparecem, bem como o Estilo Avançado se torna inabilitado. Há alguma função que deva ser atividada para manter eles habilitados ou é erro do sistema?

**Comment by pedrohsoaresadv** [comment]
Olá @HamandaCabral 

Certamente alguma funcionalidade em seu navegador foi desabilitada, que apagar todo o seu cache de arquivos temporários assim que você o fecha.

Tente restabelecer as configurações originais do seu navegador para que as opções de favoritos e estilo avançado possam gravar as suas últimas informações.
