### ISSUE TITLE
Botão "Assinar", durante a edição um documento, não salva a versão atual antes de assinar

### ISSUE THREAD

**Issue by joseolinda** [SEI-Pro/sei-pro#36]
O comportamento padrão do SEI é: ao editar/criar um documento, se clicarmos em assinar, ele salva a versão atual e leva para a função de assinatura. Contudo, usando a extensão, o botão de assinar não salva a versão atual, levando apenas para a função se assinar.

**Comment by pedrohsoaresadv** [comment]
Prezado @joseolinda 

Depois de muita pesquisa, praticamente rescrevendo do zero o SEI Pro, pude identificar que esse problema estava se refletindo por diversas extensões usadas no Chrome, inclusive o Google Tradutor. Aparentemente a última atualização do Chrome (Versão 104.0.5112.79) ocasionou algum comportamento indesejado na função nativa do SEI que, combinado com extensões, não executava a rotina de habilita o botão de Salvar do editor do SEI.
A solução aplicada no SEI Pro foi forçar o carregamento do botão de salvar caso o editor não carregue adequadamente essa função nativa.

Espero que tenha sido claro e obrigado pelo feedback
