### ISSUE TITLE
Erro ao abrir processo sigiloso

### ISSUE THREAD

**Issue by lages333** [SEI-Pro/sei-pro#37]
Todas as vezes que tento abrir um processo sigiloso a extensão não permite que eu tenha acesso ao processo.

O pop-up de solicitação de senha do processo fica abrindo o tempo todo, ai quando tento fechar o pop-up sou redirecionado para a tela inicial do SEI e não consigo acessar o conteúdo do processo. Quando eu digito a senha correta o pop-up aparece outra vez e fica assim infinitamente.

Parece que a extensão não funciona com os processos sigilosos.

**Comment by RayAshk** [comment]
O mesmo está acontecendo com todos que usam o sistema (de SEI passou a se chamar SUPER). 
Alguém saberia como resolver?

**Comment by pedrohsoaresadv** [comment]
Olá @RayAshk e @lages333 

Acabamos de lançar a versão 1.2. Nela corrigi alguns bugs relacionados ao acesso a processos sigilogos, conforme descrito em seu relato. 

Peço que verifique novamente a partir dessa versão mais recente. Caso o erro persista me informe por aqui.
