### ISSUE TITLE
Erro ao anexar arquivo

### ISSUE THREAD

**Issue by jhonnatansemler** [SEI-Pro/sei-pro#38]
Olá,

       Utilizando a extensão na última versão do Chrome 104.0.5112.101, ao anexar um arquivo externo a um processo o SEI Pro exibe uma mensagem "Anexo NOME_DO_ARQUIVO.pdf não encontrado" 

![image](https://user-images.githubusercontent.com/4230083/187539045-c49af49d-4804-416b-937e-0ac6662c1526.png)

**Comment by pedrohsoaresadv** [comment]
Olá @jhonnatansemler 

Fico feliz que tenha gostado do SEI Pro ;)

Acabamos de lançar a versão 1.2. Nela corrigi alguns bugs relacionados ao upload de arquivos, conforme descrito em seu relato. Peço que verifique novamente a partir dessa versão mais recente. 

Deixe-nos saber se o bug ainda está visível para você.
