### ISSUE TITLE
Documentação da funcionalidade "Favoritos"

### ISSUE THREAD

**Issue by tuliogit** [SEI-Pro/sei-pro#41]
Seria interessante melhorar a documentação que trata dos favoritos para informar ao usuário que deletar o cache do navegador também faz deletar os favoritos. Perdi todos os meus ao deletar  cache e cookies.

**Comment by pedrohsoaresadv** [comment]
@tuliogit 

Infelizmente o sistema de arquivos do navegador, apesar de possuir certa persistência, ainda está vulneráveis a remoção manual do cache.

Relativo a documentação, vou adicionar sua sugestão, alertando desta vulnerabilidade.

Aproveito para informar que essa funcionalidade está sendo revisada, para encontrar outras soluções de base de dados persistentes, sem utilizar dados voláteis do navegador.
