### ISSUE TITLE
Não é possível tornar um processo não atribuído a alguma pessoa

### ISSUE THREAD

**Issue by knvzzz** [SEI-Pro/sei-pro#42]
Após confirmada a seleção do espaço em branco no "Editar atribuição de processo" o processo deveria não ficar atribuído a ninguém.

Contudo ao invés disso ele atribuí ao último nome na lista.

**Comment by pedrohsoaresadv** [comment]
@knvzzz 

Obrigado pelo report de bug. Identifiquei o problema e já providenciei a correção. Será lançado na próxima atualização do SEI Pro
