### ISSUE TITLE
Corrigir links da documentação

### ISSUE THREAD

**Issue by tiagoalves-dev** [SEI-Pro/sei-pro#43]
Alguns links da página https://sei-pro.github.io/sei-pro/ do github pages estão quebrados (acredito que estejam no formato antigo).

**Comment by pedrohsoaresadv** [comment]
Olá @tiagoalves-dev 

Acabamos de lançar a versão 1.2. Nela corrigi alguns links e atualizei o guia de utilização.

Caso encontre algum link específico quebrado, por favor me informe por aqui.
