### ISSUE TITLE
Seleção de texto não contínuo

### ISSUE THREAD

**Issue by Meddeirosz** [SEI-Pro/sei-pro#45]
Ao manter a tecla "Alt" pressionada e tentar selecionar vários trechos de texto, o sistema remove a seleção anterior, sendo possível apenas selecionar uma palavra por vez. O comando não funciona.

**Comment by pedrohsoaresadv** [comment]
@Meddeirosz 

Poderia me descrever em qual cenário está tentando utilizar essa seleção. Seria no editor de documentos do SEI? Está se referindo da ferramenta de colar estilos?

**Comment by opedrosoares** [comment]
Fechado por inatividade, sem prejuízo de reabertura caso necessário.
