### ISSUE TITLE
Problema no Chrome com Versão SEI 4.0 - Menu invisivel

### ISSUE THREAD

**Issue by MasterZardoz** [SEI-Pro/sei-pro#46]
Estou com a versão SEI 4.0 e com a extensão instalada "esconde" texto da barra lateral esquerda (menu), os textos ficam como se fossem com a mesma cor do fundo e os ícones no inicio das linhas do menu aparecem mas com tipo 85% de transparência. Não tinha este problema antes do SEI 4 e no Firefox não está com este problema, mas como desde inicio (antes de SEI 4) Favoritos que considero importante não funciona. Também percebi que com SEI 4 perdemos tanto no Chrome quanto Firefox a duplicação de processo.

**Comment by opedrosoares** [comment]
Obrigado pelo report.

Corrigido na próxima versão a ser publicada (1.5.3.2)
