### ISSUE TITLE
Barra lateral de Menu

### ISSUE THREAD

**Issue by Replopes** [SEI-Pro/sei-pro#49]
A barra lateral de Menu fica aparecendo a cada click diferente em um documento dentro do processo SEI. Existe alguma forma de minimizar a barra de vez, sem ter que a cada vez que eu entrar em um documento diferente eu ter que minimizá-lo clicando no botão "Menu".

Obrigado

**Comment by cassiors** [comment]
Prezados boa tarde, aqui a mesma coisa, o menu antes da versão 4.0, ficava oculto de forma automática agora é aleatório, hora fica e tem momentos que só oculta ao clicar no "Menu".

**Comment by opedrosoares** [comment]
Obrigado pelo report.

Corrigido na próxima versão a ser publicada (1.5.3.2)
