### ISSUE TITLE
Refresh e deslocamento da lista de processos

### ISSUE THREAD

**Issue by Luis-Otavio-Gouveia** [SEI-Pro/sei-pro#50]
Utilizando Google Chrome 111.0.5563.147 64 bits e SEI Pro Lab 1.3
Ao retornar da edição de um documento para a tela de lista de processos, o script entra em loop, exibindo e ocultando um ícone de lupa logo acima da barra de títulos, o que faz com que a lista de processos fique movendo-se ininterruptamente para cima e para baixo, dificultando o clicar sobre um processo específico
![Tela com lupa](https://user-images.githubusercontent.com/129520888/229139434-e654db8f-00ac-40dc-a41f-ad9552fcfe29.png)
![Tela sem lupa](https://user-images.githubusercontent.com/129520888/229139443-cb47e8ad-544a-4cad-bb87-1f4516273ec8.png)

**Comment by seipro** [comment]
Olá @Luis-Otavio-Gouveia 

A versão > 1.4 corrigiu o problema informado.
