### ISSUE TITLE
Erro em Processos Sigilosos

### ISSUE THREAD

**Issue by barretoesa** [SEI-Pro/sei-pro#51]
A edição de processos sigilosos funcionam normalmente enquanto a extensão SEI!PRO não estar ativada, mas, se ativarmos a extensão, ao acessarmos um documento para edição dentro deste processo sigiloso, o sistema pede senha indefinidamente.

**Comment by seipro** [comment]
Olá @barretoesa 

A versão > 1.4 corrigiu o problema informado.
