### ISSUE TITLE
Botão "Incluir documento" duplicado

### ISSUE THREAD

**Issue by tiagoalves-dev** [SEI-Pro/sei-pro#52]
Navegador: Brave 1.49.132 (e versões anteriores)
Versão SEIPro: 1.3
![image](https://user-images.githubusercontent.com/67431008/230920186-328b1284-dde6-4238-8051-1d257862c38e.png)

Botão "Incluir documento" está duplicado.

**Comment by seipro** [comment]
Olá @tiagoalves-dev 

A versão > 1.4 corrigiu o problema informado.
