### ISSUE TITLE
Conflito Versão SEI PRo

### ISSUE THREAD

**Issue by aline101020** [SEI-Pro/sei-pro#53]
Instalei a versão SEI Pro no meu Chrome. Maravilhosos os recursos. Ocorre que está entrando em conflito com meu SEI.. quando tento inserir um documento externo, primeiramente ele diz que nao achou o documento, e posteriormente ele insere o mesmo duplicado.
Tela treme e muitas vezes a barra de rolagem trava na edição de documentos.

**Comment by seipro** [comment]
Olá @aline101020 

A versão > 1.4 corrigiu o problema informado.
