### ISSUE TITLE
Numeração de documentos na árvore não está funcionando corretamente

### ISSUE THREAD

**Issue by rafaelsantosdetranro** [SEI-Pro/sei-pro#56]
A numeração dos documentos na árvore de processo não está funcionando no Microsoft Edge, e no Google Chrome apresenta erro na contagem quando o processo tem mais de uma pasta (não testei em outro navegador). Segue print anexo do problema.

![Print - Erro na enumeração de documentos na árvore - SEI](https://github.com/SEI-Pro/sei-pro/assets/133885106/b05a39e9-4902-4d52-bf08-0ab6634437c3)

**Comment by opedrosoares** [comment]
Obrigado pelo report.

Corrigido na próxima versão a ser publicada (1.5.3.2)
