### ISSUE TITLE
SEI Pro conflita com Chrome

### ISSUE THREAD

**Issue by Alinerigojardim** [SEI-Pro/sei-pro#58]
a versão atual do SEI Pro deixa meu sistema muito lento, pesado. muitas vezes nao deixa enviar documentos e fica atualizado a arvore a todo momento. Gosto muito desta versão, pra mim é a melhor, q possui mais recursos... porém, está impossível de trabalhar.

**Comment by opedrosoares** [comment]
Olá @Alinerigojardim 

Não consegui vislumbrar o erro relatado para poder investigar.

Para tratar melhor seu caso, me contato pelo grupo do SEI Lab: [http://bit.ly/SEI_Lab](http://bit.ly/SEI_Lab)
