### ISSUE TITLE
Subseção não reinicia contagem

### ISSUE THREAD

**Issue by maxwelfreitas** [SEI-Pro/sei-pro#60]
No módulo enumerar norma a numeração da subseção não reinicia dentro de uma nova seção ou capítulo, por exemplo:

<img width="122" alt="image" src="https://github.com/SEI-Pro/sei-pro/assets/60654106/d17ede93-6f54-4321-8361-3913920b099f">

**Comment by opedrosoares** [comment]
Obrigado pelo report.

Corrigido na próxima versão a ser publicada (1.5.3.2)
