### ISSUE TITLE
Preenchimento automático de senha

### ISSUE THREAD

**Issue by cassiors** [SEI-Pro/sei-pro#62]
Prezados bom dia

Vocês estão com problemas com o preenchimento automático de senhas, ao logar e na assinatura de documentos em geral?
Não sei se isso é geral na versão 4.X ou do plugin do sei pro.

**Comment by opedrosoares** [comment]
Prezado @cassiors 

Na verdade esse comportamento é nativo do SEI. Por questões negociais dos administradores do SEI (TRF4) foi tomada essa decisão questionável de impedir o preenchimento automático de senha no SEI > 4.0.

Por isso foi criada nova funcionalidade no SEI Pro, chamada "Autopreencher senha no login (SEI >= 4.0)", disponível para ativação nas configurações da extensão
