### ISSUE TITLE
Datas Erradas de Legislação - 31 de dezembro de 2022

### ISSUE THREAD

**Issue by VitorVillarino** [SEI-Pro/sei-pro#63]
Bom dia,

Descobrimos alguns erros na datas que são inseridas na funcionalidade "inserir link de legislação". Esses erros acontecem principalmente com as legislações de 01 de janeiro de 2023 (aparecem como 31 de dezembro de 2022).

Por exemplo: a Medida Provisória nº 1.154, o Decreto nº 11.352 e Decreto nº 11.329.

São Leis e Decretos de estrutura do novo governo e que nem poderiam ter sido editados em 31 de dezembro de 2022.

Muito obrigado e parabéns pelo trabalho.

**Comment by opedrosoares** [comment]
Olá, @VitorVillarino 

Verifiquei o script que busca os dados no site do planalto para gravá-lo em banco de dados próprio do SEI Pro, não encontrei anomalias no seu funcionamento. 

Suspeito que a assinatura declara no site do planalto foi corrigida posteriormente, após a pesquisa rotineira que faço. 

De qualquer forma, as datas foram corrigidas. Obrigado pelo report.
