### ISSUE TITLE
SEI 4.0.9 - Menu Interessados - Botão Pesquisar processos relacionados não está funcionando

### ISSUE THREAD

**Issue by eduardolustoza** [SEI-Pro/sei-pro#66]
Prezados,

O botão de Pesquisar processos relacionados, quando utilizado dentro de um processo, não está funcionando na versão 4.0.9.

![image](https://github.com/SEI-Pro/sei-pro/assets/28105718/8a1e7051-4b59-4c26-beb3-e96cba903337)

**Comment by opedrosoares** [comment]
Obrigado pelo report.

Corrigido na próxima versão a ser publicada (1.5.3.2)
