### ISSUE TITLE
link para upload não encontrado 

### ISSUE THREAD

**Issue by marileadgad** [SEI-Pro/sei-pro#67]
bom dia
mesmo que o processo esteja comigo, não estou conseguindo mais anexar anexos com o mouse....
link para upload não encontrado 
<img width="203" alt="image" src="https://github.com/SEI-Pro/sei-pro/assets/144039756/5e1691eb-7deb-4fe7-a902-8396e20828eb">

**Comment by rfginfo91** [comment]
Estou com o mesmo problema, não faz upload dos arquivos arrastados.

Tentei com outros navegadores e nada.

Tentei verificar com as configurações da extensão e não consegui.

O problema é que não tenho acesso à configurar o servidor, não sei se tem alguma opção para habilitar isso no Sistema, gostaria que alguém pudesse me ajudar nisso.
![Capturar](https://github.com/SEI-Pro/sei-pro/assets/146362031/cffb4fb8-af9e-4507-a5f6-9f4398b9f1c7)

**Comment by cedmas** [comment]
Tb estou com o mesmo problema. Alguém encontrou a solução??
![image](https://github.com/SEI-Pro/sei-pro/assets/59168281/7f33ef27-40ef-437d-93e2-51c1390bda50)

**Comment by opedrosoares** [comment]
Prezados @cedmas @marileadgad  e @rfginfo91 

O SEI 4.1 modificou a estrutura interna do código, quebrando algumas das funcionalidades do SEI Pro.

Felizmente, após alguns aprimoramentos no SEI Pro, consegui restabelecer as ferramentas de upload de documentos arrastando e soltando, duplicar documentos e copiar documento para outro processo.

A versão 1.5.5.4 do SEI Pro já contempla essas melhorias.

**Comment by marileadgad** [comment]
muuuuuuuuuito obrigada!!!

Em sáb., 6 de jan. de 2024 às 16:28, Pedro Soares ***@***.***>
escreveu:
