### ISSUE TITLE
Link quebrado na página de documentação

### ISSUE THREAD

**Issue by jfzanato** [SEI-Pro/sei-pro#68]
No endereço https://sei-pro.github.io/sei-pro/pages/ESTILOAVANCADO.html, a URL da imagem aponta para um local que não existe.

https://sei-pro.github.io/sei-pro/img/tela-estiloavancado_.gif

![image](https://github.com/SEI-Pro/sei-pro/assets/17161027/65acb677-a182-45b1-acf9-7237713108e5)

Ao testar dessa forma, a imagem funciona.

https://sei-pro.github.io/sei-pro/img/tela-estiloavancado.gif

**Comment by opedrosoares** [comment]
Obrigado pelo report. Link corrigido!
