### ISSUE TITLE
SEI parou de funcionar na versão 4.0.10

### ISSUE THREAD

**Issue by Carol-1987** [SEI-Pro/sei-pro#69]

**Comment by maguecbr** [comment]
O mesmo aqui. É como se a extensão tivesse desaparecido.

**Comment by tamycs** [comment]
Aqui tbm parou!!

**Comment by opedrosoares** [comment]
A pedido do SEI MG, SEI SP e  SEI RJ, desativei temporariamente o SEI Pro nessas entidades.

A equipe técnica desses estados estavam trabalhando pra verificar a sobrecarga no sistema, e me solicitaram o desativamento para isolarem qualquer variável de impacto.

Para SP e RJ já foi restabelecido o funcionamento da extensão, após investigação e exclusão da hipótese ser o SEI Pro. Para MG será reestabelecido no dia 10/09/2023.

Aproveito para convidarem para o Grupo SEI Lab, lá são divulgadas atualizações em tempo real sobre a ferramenta

[http://bit.ly/SEI_Lab](http://bit.ly/SEI_Lab)

**Comment by maguecbr** [comment]
O SEI Pro sumiu novamente em SP.

**Comment by tamycs** [comment]
O Sei Sp continua sem funcionar. Alguma novidade??

**Comment by opedrosoares** [comment]
@maguecbr e @tamycs 

Após tratativas com o SEI SP (Prodesp), o SEI Pro foi reestabelecido.

Estamos viabilizando melhoras para que esteja de acordo com os administradores do sistema nesse estado.
