### ISSUE TITLE
Loop Infinito no Alinhamento

### ISSUE THREAD

**Issue by VitorVillarino** [SEI-Pro/sei-pro#71]
Bom dia,

Primeiramente, parabéns pelo trabalho. O Sei-Pro é sensacional.
Me deparei aparentemente com um bug na funcionalidade de alinhamento, que entra em loop chamando a função setAlignText até estourar a pilha. O sistema até dá uma travada.

Acredito que ele ocorra quando está no final do documento e tenta alinhar algo, mas não tenho certeza disso.

Segue um print do console:
![image](https://github.com/SEI-Pro/sei-pro/assets/28730712/ae7ff4ca-bbf8-4d55-aab0-ed63f7194dce)

**Comment by opedrosoares** [comment]
@VitorVillarino 

Não consegui reproduzir o erro informado. Imagino que seja algo relacionado ao estilo aplicado ao parágrafo.

Para tratar melhor seu caso, me contato pelo grupo do SEI Lab: [http://bit.ly/SEI_Lab](http://bit.ly/SEI_Lab)
