### ISSUE TITLE
Problemas com SEI PRO na versão SEI4

### ISSUE THREAD

**Issue by d3vb00t** [SEI-Pro/sei-pro#72]
Funcionalidades básicas do SEI (copiar peças, arrastar anexos para o processo e inserir anotações) não funcionam mais e este erro aparece no debugger:
<img width="523" alt="erro sei pro" src="https://github.com/SEI-Pro/sei-pro/assets/83996124/e3e74f97-17c8-44c6-abdc-5211570730bb">

**Comment by Othon3** [comment]
Também notamos o erro e não conseguimos mais usar as principais funções da extensão.
Funções importantíssimas deixaram de funcionar (como arrastar e soltar arquivos (anexos) PDF e outros nos processos do SEI.
TODAS AS PESSOAS que utilizam o SEI cotidianamente foram afetadas.
POr favor revisem a versão, ou verifiquem a compatibilidade dessa importante extensão para o uso do sistema

nem o histórico de processos está registrando mais, desde o dia 20/10/2023. 

SEI ver 4.1.1 
SEI Pro Versão 1.5.4.9 
Chrome Versão 119.0.6045.105 (Versão oficial) 64 bits

**Comment by tamycs** [comment]
Simplesmente o Sei não funciona mais (SP)

**Comment by opedrosoares** [comment]
Prezado @Othon3 e @d3vb00t 

O SEI 4.1 modificou a estrutura interna do código, quebrando algumas das funcionalidades do SEI Pro.

Felizmente, após alguns aprimoramentos no SEI Pro, consegui restabelecer as ferramentas de upload de documentos arrastando e soltando, duplicar documentos e copiar documento para outro processo.

A versão 1.5.5.4 do SEI Pro já contempla essas melhorias.
