### ISSUE TITLE
Erro em tela de alternar unidades

### ISSUE THREAD

**Issue by carolfreirer** [SEI-Pro/sei-pro#73]
Oi Pedro 😄 

Quando vamos alterar uma unidade ele aparece issaí no vídeo. Quando entro no processo, ele fica normal, mas nessa tela de alterar unidade ele dá esse erro.

https://github.com/SEI-Pro/sei-pro/assets/76488169/03d3d1ea-4731-4ed0-ae73-0920ae033957

**Comment by opedrosoares** [comment]
Ei @carolfreirer 

Acabo de atualizar a extensão para a versão 1.5.5.3, com a correção dos filtros e acesso a processos sigilosos.

Veja se corrigiu ;)
