### ISSUE TITLE
Função ordenar documentos na arvore do processo não está funcionando. Não aparece o botão para movimentar documento. 

### ISSUE THREAD

**Issue by Calospds** [SEI-Pro/sei-pro#74]
[Erro_Ord_Doc.docx](https://github.com/SEI-Pro/sei-pro/files/13416114/Erro_Ord_Doc.docx)

**Comment by opedrosoares** [comment]
@Calospds 

Obrigado pelo report, será corrigido na próxima atualização (1.5.5.4)
