### ISSUE TITLE
Botão de estilo avançado sumiu e cores de marcadores personalizados não funcionam

### ISSUE THREAD

**Issue by RafaelSLopes** [SEI-Pro/sei-pro#76]
Prezado,
Gostaria de relatar que ao usar a extensão em meu computador pessoal o botão de estilo avançado sumiu e as cores personalizadas dos marcadores não funcionam. Tentei excluir os temporários, reinstalar a extensão, mas continua o problema. 
No computador institucional funciona normalmente.

**Comment by opedrosoares** [comment]
Olá @RafaelSLopes 

Não consegui vislumbrar o erro relatado para poder investigar.

Para tratar melhor seu caso, me contato pelo grupo do SEI Lab: http://bit.ly/SEI_Lab

**Comment by Lidiana24** [comment]
> Prezado, Gostaria de relatar que ao usar a extensão em meu computador pessoal o botão de estilo avançado sumiu e as cores personalizadas dos marcadores não funcionam. Tentei excluir os temporários, reinstalar a extensão, mas continua o problema. No computador institucional funciona normalmente.

Estou com o mesmo problema, no entanto, no Chrome não funciona em nenhum computador as cores personalizadas. A minha instituição ainda não atualizou para a versão SEI 4.0 Conseguiram identificar o problema?

**Comment by Lidiana24** [comment]
> Prezado, Gostaria de relatar que ao usar a extensão em meu computador pessoal o botão de estilo avançado sumiu e as cores personalizadas dos marcadores não funcionam. Tentei excluir os temporários, reinstalar a extensão, mas continua o problema. No computador institucional funciona normalmente.

Estou com o mesmo problema, no entanto, no Chrome não funciona em nenhum computador as cores personalizadas. A minha instituição ainda não atualizou para a versão SEI 4.0 Conseguiram identificar o problema?
