### ISSUE TITLE
Arrastar e soltar PDF anexo nao funiconado

### ISSUE THREAD

**Issue by Othon3** [SEI-Pro/sei-pro#77]
falha ao carregar PDFs nos processos (arrastar e soltar)
Ola Pessoal.
Essa função está fazendo falta demais. Todos que utilizam o SEI aquiusam e sentem muita falta dessa função:

SEI ver 4.1.1
SEI Pro Versão 1.5.4.9
Chrome Versão 119.0.6045.105 (Versão oficial) 64 bits

Alguma possibilidade de resgatar versão ou solucionar o BUG?

**Comment by opedrosoares** [comment]
Prezado @Othon3 

O SEI 4.1 modificou a estrutura interna do código, quebrando algumas das funcionalidades do SEI Pro.

Felizmente, após alguns aprimoramentos no SEI Pro, consegui restabelecer as ferramentas de upload de documentos arrastando e soltando, duplicar documentos e copiar documento para outro processo.

A versão 1.5.5.4 do SEI Pro já contempla essas melhorias.
