### ISSUE TITLE
Erro em copiar documento

### ISSUE THREAD

**Issue by tamycs** [SEI-Pro/sei-pro#80]
Boa tarde!

Anteriormente, ao clicar na árvore do documento e na opção "copiar para" e colar o número do processo, o processo era aberto em conjunto com a cópia do documento, como se duplicasse ou enviasse o mesmo documento para outro processo.
Atualmente, ao clicar na opção, o processo abre, mas sem o documento copiado.

obs. :Não é documento externo.

Há como resolver ou é bug?

Apesar de não ser o foco do post, ressalto que a função "duplicar" também não funciona para documentos do tipo externo (pdf), procede? Seria bom se funcionasse para esse tipo de documento também.

Abs.

**Comment by opedrosoares** [comment]
@tamycs 

Acabo de atualizar a extensão para a versão 1.5.5.3, com a correção dos filtros, acesso a processos sigilosos e duplicar/copiar para...

Sobre o duplicar documento externo, ainda não é possível realizar essa ação no SEI Pro. Ainda estou superando alguns obstáculos no código para promover essa funcionalidade.

**Comment by Andre-JP** [comment]
Bom dia. 
Prezados(as),
Esta extensão é uma excelente ferramenta de produtividade. Trabalho com o SEIPro na SESMG, mas não estou conseguindo duplicar os documentos, era ótimo quando esta funcionalidade estava perfeita. Além disso, preciso de correção para exibição correta dos processos na tela CONTROLE DE PROCESSOS, pois trabalho com indicadores de uma Coordenação, preciso acompanhar os prazos e quantitativos de cada membro da equipe. Segundo minha colega houve uma divergência acerca do quantitativo de processos atribuídos a ela que seriam 11 na tela de Atribuição de Processos, mas em minha tela de Controle de Processos apareceram 8 processos. O número de processos atribuídos na tela de Atribuição de Processos deveria ser igual ao número de processos atribuídos na tela de Controle de Processos? Qual a diferença das telas de Atribuição de Processos e Controle de Processos?

<img width="1519" height="715" alt="Image" src="https://github.com/user-attachments/assets/e0d32380-eb2a-4b75-9bb8-2e9b8c88bcb0" />
<img width="1514" height="645" alt="Image" src="https://github.com/user-attachments/assets/59b492a9-f55b-4eb4-b051-7d16edae4ef8" />

At.te,
André.
