### ISSUE TITLE
Filtros nas tabelas não funcionam

### ISSUE THREAD

**Issue by TBalzani** [SEI-Pro/sei-pro#82]
Na tela inicial, na tabela de processos não está mais funcionando os filtros de processos não visualizados, processos por marcador, por atribuição e etc.
![image](https://github.com/SEI-Pro/sei-pro/assets/102154747/773516e6-5f42-4ba4-a88a-6fdceb3a42b8)

**Comment by opedrosoares** [comment]
@TBalzani 
Acabo de atualizar a extensão para a versão 1.5.5.3, com a correção dos filtros e acesso a processos sigilosos.

**Comment by opedrosoares** [comment]
@TBalzani 

A loja do Edge infelizmente leva até 1 semana para publicar as alterações, mas já está a caminho.
