### ISSUE TITLE
Funciona perfeitamente no DNIT mas não funciona na ANTT

### ISSUE THREAD

**Issue by marlonpedrini** [SEI-Pro/sei-pro#86]
Olá
Eu tenho acesso ao SEI do DNIT e da ANTT.
No DNIT o SEI PRO funciona perfeita, ja quando logo no SEI da ANTT ele não aparece, parece que não identifica que o SEI PRO está instalado.

**Comment by opedrosoares** [comment]
Olá @marlonpedrini 

A ANTT tem sua própria extensão, clone do SEI Pro, denominada ANTT Pro

https://chromewebstore.google.com/detail/antt-pro/mjpdhdikphjnhdgfachibdmcooahinoc?hl=pt-BR

O SEI Pro é desativado no domínio da ANTT justamente para não conflitar com essa outra versão.

O mesmo acontece no domínio da ANTAQ, que também possui seu clone de extensão.
