### ISSUE TITLE
Erro no link da ajuda

### ISSUE THREAD

**Issue by mgglopes** [SEI-Pro/sei-pro#9]
![image](https://user-images.githubusercontent.com/12402367/129358195-b34cd855-ae96-484b-aaa5-9db0217abc3f.png)
![image](https://user-images.githubusercontent.com/12402367/129358310-37de104d-afaf-43ba-8d52-7565ef8f0260.png)

Conforme imagens, o link para ajuda do "remover paginação" está quebrado. Erro 404.

**Comment by pedrohsoaresadv** [comment]
De fato, @mgglopes 
Na verdade a página ainda não foi criada. Irei providenciá-la.
Abraços :)
